### ISSUE TITLE
Requires Java to be installed?

### ISSUE THREAD

**Issue by JT-39** [NHSDigital/RAP_example_pipeline_python#24]
Hi, I am getting the following error:

```
Java not found and JAVA_HOME environment variable is not set.
Install Java and set JAVA_HOME to point to the Java installation directory.
```

Do I need Java to be installed? I have done:

`python -m pip install -r requirements.txt`

**Comment by warren-davies4** [comment]
Hi Jake, sorry for the delay.

Thanks for raising this issue, you've identified something missing in the guidance - yes, your machine needs to have Java installed, as the pipeline runs Spark locally, which requires Java.

Apologies for the confusion. I'll get the readme updated.
